# Generated by Django 5.1.5 on 2025-01-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionmodel',
            name='end_time',
        ),
    ]
