# Generated by Django 5.1.5 on 2025-01-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auctionmodel_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_pics_main', verbose_name='Фото лоту')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionmodel', verbose_name='Лот')),
            ],
        ),
    ]
