# Generated by Django 5.1.5 on 2025-01-27 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionimagemodel',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
