# Generated by Django 5.1.5 on 2025-02-04 15:58

import auctions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionimagemodel_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionimagemodel',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.auctionmodel', verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='auctionimagemodel',
            name='image',
            field=models.ImageField(default='auction_pics/default/original/default.png', upload_to=auctions.models.auction_image_path, verbose_name='Фото лоту'),
        ),
        migrations.AlterField(
            model_name='auctionmodel',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стартова ціна лоту'),
        ),
    ]
